# Generated by Django 6.0.4 on 2026-04-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='professor',
        ),
        migrations.AlterField(
            model_name='agenda',
            name='aula',
            field=models.CharField(max_length=200),
        ),
    ]
